var test = [ { album:
     { album_type: 'album',
       artists: [Array],
       available_markets: [Array],
       external_urls: [Object],
       href: 'https://api.spotify.com/v1/albums/5OCg9OWnL1PY4tW2ON8ssj',
       id: '5OCg9OWnL1PY4tW2ON8ssj',
       images: [Array],
       name: 'Comfort Eagle',
       release_date: '2001-07-23',
       release_date_precision: 'day',
       type: 'album',
       uri: 'spotify:album:5OCg9OWnL1PY4tW2ON8ssj' },
    artists: [ [Object] ],
    available_markets:
     [ 'AD',
       'AR',
       'AT',
       'AU',
       'BE',
       'BG',
       'BO',
       'BR',
       'CA',
       'CH',
       'CL',
       'CO',
       'CR',
       'CY',
       'CZ',
       'DE',
       'DK',
       'DO',
       'EC',
       'EE',
       'ES',
       'FI',
       'FR',
       'GB',
       'GR',
       'GT',
       'HK',
       'HN',
       'HU',
       'ID',
       'IE',
       'IL',
       'IS',
       'IT',
       'JP',
       'LI',
       'LT',
       'LU',
       'LV',
       'MC',
       'MT',
       'MX',
       'MY',
       'NI',
       'NL',
       'NO',
       'NZ',
       'PA',
       'PE',
       'PH',
       'PL',
       'PT',
       'PY',
       'RO',
       'SE',
       'SG',
       'SK',
       'SV',
       'TH',
       'TR',
       'TW',
       'US',
       'UY',
       'VN',
       'ZA' ],
    disc_number: 1,
    duration_ms: 204133,
    explicit: false,
    external_ids: { isrc: 'USSM10104611' },
    external_urls:
     { spotify: 'https://open.spotify.com/track/3OOFEF20WqtsUPcRbPY3L7' },
    href: 'https://api.spotify.com/v1/tracks/3OOFEF20WqtsUPcRbPY3L7',
    id: '3OOFEF20WqtsUPcRbPY3L7',
    name: 'Short Skirt / Long Jacket',
    popularity: 66,
    preview_url: 'https://p.scdn.co/mp3-preview/7420f9c65687e0b99707bfdaef11e17a02badf9e?cid=bb5314b285d44faca4e99f1707410b0c',
    track_number: 4,
    type: 'track',
    uri: 'spotify:track:3OOFEF20WqtsUPcRbPY3L7' } ]